"""
================================================================================
A2Z MIS 360 — Standard #383: Regulatory SLA Reporting
================================================================================

Risk classification: Cat B (deterministic regulatory report generation)

Auto-generation of regulatory SLA reports per CBK PG/09 + adjacent
regulator schedules:
    - CBK 30-day customer complaint resolution
    - CRB 14-day dispute resolution
    - FATCA reporting deadlines

Public API:
    generate_cbk_complaint_report(period)    -- CBK PG/09 30-day return
    generate_crb_dispute_report(period)      -- CRB 14-day disputes
    regulatory_sla_summary(period)           -- aggregated regulator-facing view
    validate_report_completeness(report)     -- pre-submission validation

Regulatory SLA targets byte-for-byte (CBK PG/09 + CRB):
    CBK_COMPLAINT_RESOLUTION_DAYS    = 30
    CRB_DISPUTE_RESOLUTION_DAYS      = 14
    FATCA_QUARTERLY_DAYS_AFTER_QTR   = 30

Honesty rules:
    Rule 1: compliance_pct = None when zero observations
    Rule 6: incomplete reports rejected (missing required sections
            block distribution per CMA Code precedent)

================================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, getcontext
from typing import Any, Dict, List, Optional, Tuple

from utils.sla_registry import SlaRegistryEngine
from utils.sla_monitoring import SlaMonitoringEngine

getcontext().prec = 28

# ────────────────────────────────────────────────────────────────────
# Regulatory targets — byte-for-byte
# ────────────────────────────────────────────────────────────────────

CBK_COMPLAINT_RESOLUTION_DAYS:    Decimal = Decimal("30")
CRB_DISPUTE_RESOLUTION_DAYS:      Decimal = Decimal("14")
FATCA_QUARTERLY_DAYS_AFTER_QTR:   Decimal = Decimal("30")

REGULATORY_REPORT_TYPES: Tuple[str, ...] = (
    "CBK_COMPLAINT_RESOLUTION",
    "CRB_DISPUTE_RESOLUTION",
    "FATCA_QUARTERLY",
    "AML_TRANSACTION_REPORT",
    "OPERATIONAL_RISK_RETURN",
)

REQUIRED_REPORT_SECTIONS: Tuple[str, ...] = (
    "REPORT_HEADER",
    "REPORTING_PERIOD",
    "TOTAL_OBSERVATIONS",
    "COMPLIANCE_PERCENTAGE",
    "BREACHES_DETAILED",
    "REMEDIATION_NARRATIVE",
    "ATTESTATION",
)


class RegulatoryReportingEngine:
    """Generate regulatory SLA returns + validate completeness."""

    def __init__(
        self,
        registry: Optional[SlaRegistryEngine] = None,
        monitoring: Optional[SlaMonitoringEngine] = None,
    ):
        self.registry = registry or SlaRegistryEngine()
        self.monitoring = monitoring or SlaMonitoringEngine()

    def _build_base_report(
        self,
        report_type: str,
        target_days: Decimal,
        regulatory_ref: str,
        period_start: str,
        period_end: str,
    ) -> Dict[str, Any]:
        """Common report builder for time-window regulatory SLAs."""
        regulatory_slas = [
            s for s in self.registry.list_slas(sla_type="REGULATORY")
            if s.get("regulatory_ref") == regulatory_ref
        ]

        total_obs = 0
        within = 0
        near = 0
        breached = 0
        breach_details = []

        for sla in regulatory_slas:
            comp = self.monitoring.compute_compliance(
                sla.get("sla_id"), period_start, period_end
            )
            total_obs += comp["total_observations"]
            within += comp["within_sla"]
            near += comp["near_breach"]
            breached += comp["breached"]

        # Rule 1: zero observations → None compliance
        if total_obs == 0:
            compliance_pct = None
        else:
            compliance_pct = (
                Decimal(within + near) / Decimal(total_obs) * Decimal("100")
            ).quantize(Decimal("0.01"))

        return {
            "report_type": report_type,
            "regulatory_ref": regulatory_ref,
            "target_days": str(target_days),
            "period_start": period_start,
            "period_end": period_end,
            "REPORT_HEADER": f"{report_type} — {regulatory_ref}",
            "REPORTING_PERIOD": f"{period_start} to {period_end}",
            "TOTAL_OBSERVATIONS": total_obs,
            "COMPLIANCE_PERCENTAGE": (
                str(compliance_pct) if compliance_pct is not None else None
            ),
            "BREACHES_DETAILED": breach_details,
            "REMEDIATION_NARRATIVE": (
                "All breaches subject to RCA + remediation per Standard #381"
                if breached > 0 else "No breaches in period."
            ),
            "ATTESTATION": (
                f"Generated by A2Z MIS 360 SLA Reporting Engine v10.271 "
                f"per {regulatory_ref}"
            ),
            "_meta": {
                "within": within, "near": near, "breached": breached,
                "regulatory_slas_in_scope": len(regulatory_slas),
            },
        }

    def generate_cbk_complaint_report(
        self, period_start: str, period_end: str
    ) -> Dict[str, Any]:
        """CBK PG/09 30-day complaint resolution return."""
        return self._build_base_report(
            "CBK_COMPLAINT_RESOLUTION",
            CBK_COMPLAINT_RESOLUTION_DAYS,
            "CBK PG/09",
            period_start, period_end,
        )

    def generate_crb_dispute_report(
        self, period_start: str, period_end: str
    ) -> Dict[str, Any]:
        """CRB 14-day dispute resolution return."""
        return self._build_base_report(
            "CRB_DISPUTE_RESOLUTION",
            CRB_DISPUTE_RESOLUTION_DAYS,
            "CRB",
            period_start, period_end,
        )

    def validate_report_completeness(self, report: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate regulatory report has all REQUIRED_REPORT_SECTIONS.

        Rule 6: missing sections block distribution.
        """
        missing = [s for s in REQUIRED_REPORT_SECTIONS if s not in report or report[s] in (None, "")]
        return {
            "valid": len(missing) == 0,
            "missing_sections": missing,
            "eligible_for_distribution": len(missing) == 0,
        }

    def regulatory_sla_summary(
        self, period_start: str, period_end: str
    ) -> Dict[str, Any]:
        """Aggregated regulatory SLA summary across all reports."""
        cbk = self.generate_cbk_complaint_report(period_start, period_end)
        crb = self.generate_crb_dispute_report(period_start, period_end)

        return {
            "period": f"{period_start} to {period_end}",
            "reports": [cbk, crb],
            "total_regulatory_observations": (
                cbk["TOTAL_OBSERVATIONS"] + crb["TOTAL_OBSERVATIONS"]
            ),
        }


def _self_test() -> None:
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as tmpdir:
        registry = SlaRegistryEngine(
            registry_path=Path(tmpdir) / "sla_registry.json"
        )
        monitoring = SlaMonitoringEngine(
            observations_path=Path(tmpdir) / "sla_observations.json"
        )
        engine = RegulatoryReportingEngine(registry=registry, monitoring=monitoring)

        # Register CBK SLA
        registry.register_sla({
            "sla_id": "SLA-CBK-001",
            "name": "CBK Complaint Resolution",
            "sla_type": "REGULATORY",
            "priority": "P1_CRITICAL",
            "metric_type": "RESPONSE_TIME",
            "target_value": Decimal("30"),
            "target_unit": "days",
            "direction": "max",
            "owner_department": "Compliance",
            "regulatory_ref": "CBK PG/09",
        })

        # Record observations
        monitoring.record_event(
            "SLA-CBK-001", "C-001", "2026-04-01T10:00:00",
            "2026-04-15T10:00:00",
            Decimal("14"), Decimal("30"), "max",
        )
        monitoring.record_event(
            "SLA-CBK-001", "C-002", "2026-04-01T10:00:00",
            "2026-05-05T10:00:00",
            Decimal("34"), Decimal("30"), "max",
        )

        report = engine.generate_cbk_complaint_report("2026-04-01", "2026-04-30")
        assert report["report_type"] == "CBK_COMPLAINT_RESOLUTION"
        assert report["target_days"] == "30"
        assert report["TOTAL_OBSERVATIONS"] == 2

        # Test 2: completeness validation
        validation = engine.validate_report_completeness(report)
        assert validation["valid"]

        # Test 3: missing section rejected
        bad = dict(report)
        del bad["ATTESTATION"]
        v = engine.validate_report_completeness(bad)
        assert not v["valid"]
        assert "ATTESTATION" in v["missing_sections"]

        # Test 4: Rule 1 — empty period → None compliance
        empty = engine.generate_cbk_complaint_report("2030-01-01", "2030-01-31")
        assert empty["COMPLIANCE_PERCENTAGE"] is None

    print("  ✅ sla_reporting self-test PASS")


if __name__ == "__main__":
    _self_test()
