"""scripts/generate_cbs_aggregates.py — CBS aggregate writer (v7.14 + v8.10).

Populates `cbs_data/*_aggregate.json` files that the v7.10/v7.11 FLEXCUBE
Anti-Corruption Layer aggregator (`utils/flexcube_aggregator.py`) reads
when mode=synthetic and aggregate files are present.

Without these files, the ACL falls back to hardcoded demo defaults inside
`flexcube_aggregator._loan_portfolio_demo_defaults()` etc. With these
files in place, `mode=synthetic` becomes a meaningful test environment
that mirrors what `mode=live` would return — same dict contract, same
field names, same aggregate values.

Two modes of operation:
    1. **Generative mode (default):** writes the same demo-defaults values
       as JSON files. Lets the ACL synthetic-tier path become exercisable
       without a real CBS data dump.
    2. **Computed mode (--from-cbs, v8.10):** if `cbs_data/customers.json`,
       `cbs_data/accounts.json`, and `cbs_data/transactions.json` are
       present (Joshua's local A2Z Blueprint CBS simulation: 700K
       customers, 1.2M accounts, 50K transactions, 35 branches),
       aggregates from them. Computes loan portfolio (gross outstanding,
       segment + IFRS 9 stage breakdown), deposit book (LDR, stability +
       product + segment breakdown), NPL (stage 3 + aging buckets),
       customer base (tenure + channel + KYC risk bands), and dormant
       accounts (dormancy bands + segment counts + reactivation potential
       + latent value). Falls back to generative mode with a clear
       message if any required source file is missing.

Outputs (5 files):
    cbs_data/loans_aggregate.json     — for fetch_loan_portfolio_aggregate()
    cbs_data/deposits_aggregate.json  — for fetch_deposit_book_aggregate()
    cbs_data/npl_aggregate.json       — for fetch_npl_aggregate()
    cbs_data/customer_aggregate.json  — for fetch_customer_base_aggregate()
    cbs_data/dormant_aggregate.json   — for fetch_dormant_accounts_aggregate()

Each file is byte-identical in shape to what the demo defaults return —
same keys, same string Decimals, same ordering. The ACL doesn't know or
care whether the values came from these generated files or from demo
defaults; it just stamps `data_source = "cbs_synthetic"` instead of
`data_source = "demo_defaults"`.

Usage:
    python -m scripts.generate_cbs_aggregates [--from-cbs] [--out PATH]

Exit codes:
    0 — all 5 files written successfully
    1 — write error
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict


# ══════════════════════════════════════════════════════════════════
# Aggregate generators (mirror flexcube_aggregator demo defaults)
# ══════════════════════════════════════════════════════════════════

def loan_portfolio_aggregate() -> Dict[str, Any]:
    """Generate loans_aggregate.json content.

    Mirrors flexcube_aggregator._loan_portfolio_demo_defaults() so the
    ACL produces identical output regardless of which path it takes.
    """
    return {
        "_doc": (
            "v7.14 CBS aggregate — generated by "
            "scripts/generate_cbs_aggregates.py. Consumed by "
            "utils/flexcube_aggregator.fetch_loan_portfolio_aggregate() "
            "when mode=synthetic. Tier-2 Kenya bank baseline."
        ),
        "_schema_version": "1.0",
        "gross_outstanding_kes": "80000000000",
        "by_segment_kes": {
            "RETAIL_INDIVIDUAL": "20000000000",
            "SME": "18000000000",
            "CORPORATE": "32000000000",
            "REAL_ESTATE": "8000000000",
            "STAFF_LOANS": "2000000000",
        },
        "by_stage_kes": {
            "STAGE_1": "68000000000",
            "STAGE_2": "4000000000",
            "STAGE_3": "8000000000",
        },
        "weighted_avg_pd_pct": "3.2",
        "average_lgd_pct": "45.0",
    }


def deposits_aggregate() -> Dict[str, Any]:
    """Generate deposits_aggregate.json content."""
    return {
        "_doc": (
            "v7.14 CBS aggregate — consumed by "
            "fetch_deposit_book_aggregate() when mode=synthetic."
        ),
        "_schema_version": "1.0",
        "total_deposits_kes": "110000000000",
        "loan_to_deposit_ratio_pct": "72.73",
        "by_stability_tier_kes": {
            "RETAIL_STABLE": "55000000000",
            "RETAIL_LESS_STABLE": "22000000000",
            "OPERATIONAL_DEPOSITS": "16500000000",
            "NON_OPERATIONAL_CORPORATE": "11000000000",
            "FINANCIAL_INSTITUTIONS": "5500000000",
        },
        "by_product_kes": {
            "CURRENT_ACCOUNTS": "33000000000",
            "SAVINGS_ACCOUNTS": "44000000000",
            "FIXED_DEPOSITS": "27500000000",
            "CALL_DEPOSITS": "5500000000",
        },
        "by_segment_kes": {
            "RETAIL_INDIVIDUAL": "66000000000",
            "SME": "16500000000",
            "CORPORATE": "22000000000",
            "FINANCIAL_INSTITUTIONS": "5500000000",
        },
    }


def npl_aggregate() -> Dict[str, Any]:
    """Generate npl_aggregate.json content."""
    return {
        "_doc": (
            "v7.14 CBS aggregate — consumed by "
            "fetch_npl_aggregate() when mode=synthetic."
        ),
        "_schema_version": "1.0",
        "stage_3_kes": "8000000000",
        "loan_book_basis_kes": "80000000000",
        "npl_ratio_pct": "10.00",
        "by_aging_kes": {
            "DAYS_91_180": "3000000000",
            "DAYS_181_365": "3500000000",
            "DAYS_OVER_365": "1500000000",
        },
    }


def customer_aggregate() -> Dict[str, Any]:
    """Generate customer_aggregate.json content."""
    return {
        "_doc": (
            "v7.14 CBS aggregate — consumed by "
            "fetch_customer_base_aggregate() when mode=synthetic. "
            "700K customers matching A2Z Blueprint simulation."
        ),
        "_schema_version": "1.0",
        "total_customers": 700_000,
        "by_segment_count": {
            "RETAIL_INDIVIDUAL": 595_000,
            "SME": 70_000,
            "CORPORATE": 28_000,
            "STAFF": 7_000,
        },
        "by_tenure_band_count": {
            "0_TO_1_YEAR": 105_000,
            "1_TO_3_YEARS": 175_000,
            "3_TO_5_YEARS": 140_000,
            "OVER_5_YEARS": 280_000,
        },
        "by_onboarding_channel_count": {
            "BRANCH": 350_000,
            "DIGITAL_ONBOARDING": 210_000,
            "AGENT": 105_000,
            "REFERRAL": 35_000,
        },
        "by_kyc_risk_band_count": {
            "LOW": 525_000,
            "MEDIUM": 140_000,
            "HIGH": 35_000,
            "PROHIBITED": 0,
        },
        "monthly_growth_rate_pct": "0.8",
    }


def dormant_aggregate() -> Dict[str, Any]:
    """Generate dormant_aggregate.json content."""
    return {
        "_doc": (
            "v7.14 CBS aggregate — consumed by "
            "fetch_dormant_accounts_aggregate() when mode=synthetic. "
            "12% dormancy rate per industry typical."
        ),
        "_schema_version": "1.0",
        "total_dormant": 84_000,
        "customer_basis_count": 700_000,
        "dormancy_rate_pct": "12.00",
        "by_dormancy_band_count": {
            "DAYS_90_TO_180": 42_000,
            "DAYS_181_TO_365": 25_200,
            "OVER_365_DAYS": 16_800,
        },
        "by_segment_count": {
            "RETAIL_INDIVIDUAL": 75_600,
            "SME": 5_880,
            "CORPORATE": 1_680,
            "STAFF": 840,
        },
        "reactivation_potential_count": 12_600,
        "avg_balance_per_dormant_kes": 8_500,
        "estimated_latent_value_kes": "714000000",
    }


# ══════════════════════════════════════════════════════════════════
# Writer
# ══════════════════════════════════════════════════════════════════

GENERATORS = [
    ("loans_aggregate.json", loan_portfolio_aggregate),
    ("deposits_aggregate.json", deposits_aggregate),
    ("npl_aggregate.json", npl_aggregate),
    ("customer_aggregate.json", customer_aggregate),
    ("dormant_aggregate.json", dormant_aggregate),
]


# ══════════════════════════════════════════════════════════════════
# v8.10 — Computed-from-CBS aggregation (closes v8.6 retrospective ack #5)
# ══════════════════════════════════════════════════════════════════

def _load_cbs_source(out_dir: Path, filename: str) -> Any:
    """Load a CBS source file (customers.json / accounts.json / transactions.json).

    Returns parsed content, or None if the file is missing/unreadable.
    """
    path = out_dir / filename
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _check_cbs_sources(out_dir: Path) -> Dict[str, bool]:
    """Return presence map for the 3 expected CBS source files."""
    return {
        "customers.json": (out_dir / "customers.json").exists(),
        "accounts.json": (out_dir / "accounts.json").exists(),
        "transactions.json": (out_dir / "transactions.json").exists(),
    }


def _safe_decimal_str(value: float) -> str:
    """Convert a numeric to a decimal-style string with no trailing decimals
    when the number is integer-valued (matches demo defaults convention)."""
    if value == int(value):
        return str(int(value))
    return f"{value:.2f}"


def _aggregate_loans_from_cbs(accounts: list) -> Dict[str, Any]:
    """Aggregate loan portfolio from accounts.json. v8.10."""
    loan_accounts = [
        a for a in accounts
        if a.get("account_type", "").upper() in ("LOAN", "MORTGAGE", "TERM_LOAN")
    ]
    gross_total = sum(
        float(a.get("outstanding_balance", a.get("balance", 0)))
        for a in loan_accounts
    )
    by_segment: Dict[str, float] = {}
    by_stage: Dict[str, float] = {}
    for a in loan_accounts:
        seg = a.get("segment", a.get("customer_segment", "RETAIL"))
        bal = float(a.get("outstanding_balance", a.get("balance", 0)))
        by_segment[seg] = by_segment.get(seg, 0) + bal
        stage = a.get("ifrs9_stage", "STAGE_1")
        by_stage[stage] = by_stage.get(stage, 0) + bal

    return {
        "_doc": "Computed loan portfolio aggregate (v8.10 --from-cbs).",
        "_schema_version": "1.0",
        "gross_outstanding_kes": _safe_decimal_str(gross_total),
        "by_segment_kes": {k: _safe_decimal_str(v) for k, v in by_segment.items()},
        "by_stage_kes": {k: _safe_decimal_str(v) for k, v in by_stage.items()},
        "weighted_avg_pd_pct": "5.0",  # PD/LGD require risk-engine inputs
        "average_lgd_pct": "45.0",      # not derivable from raw CBS alone
    }


def _aggregate_deposits_from_cbs(accounts: list, loan_total: float) -> Dict[str, Any]:
    """Aggregate deposit book from accounts.json. v8.10."""
    deposit_accounts = [
        a for a in accounts
        if a.get("account_type", "").upper() in (
            "SAVINGS", "CHECKING", "CURRENT", "FIXED_DEPOSIT", "FD")
    ]
    total_deposits = sum(
        float(a.get("balance", 0)) for a in deposit_accounts
    )
    by_product: Dict[str, float] = {}
    by_segment: Dict[str, float] = {}
    by_stability: Dict[str, float] = {}
    for a in deposit_accounts:
        prod = a.get("account_type", "OTHER").upper()
        seg = a.get("segment", a.get("customer_segment", "RETAIL"))
        stability = "STABLE" if prod in ("FIXED_DEPOSIT", "FD") else "VOLATILE"
        bal = float(a.get("balance", 0))
        by_product[prod] = by_product.get(prod, 0) + bal
        by_segment[seg] = by_segment.get(seg, 0) + bal
        by_stability[stability] = by_stability.get(stability, 0) + bal

    ldr = (loan_total / total_deposits * 100.0) if total_deposits > 0 else 0.0
    return {
        "_doc": "Computed deposit book aggregate (v8.10 --from-cbs).",
        "_schema_version": "1.0",
        "total_deposits_kes": _safe_decimal_str(total_deposits),
        "loan_to_deposit_ratio_pct": f"{ldr:.1f}",
        "by_stability_tier_kes": {k: _safe_decimal_str(v) for k, v in by_stability.items()},
        "by_product_kes": {k: _safe_decimal_str(v) for k, v in by_product.items()},
        "by_segment_kes": {k: _safe_decimal_str(v) for k, v in by_segment.items()},
    }


def _aggregate_npl_from_cbs(accounts: list, loan_total: float) -> Dict[str, Any]:
    """Aggregate NPL inventory from accounts.json. v8.10."""
    stage3_accounts = [
        a for a in accounts
        if a.get("account_type", "").upper() in ("LOAN", "MORTGAGE", "TERM_LOAN")
        and a.get("ifrs9_stage", "STAGE_1") == "STAGE_3"
    ]
    stage3_total = sum(
        float(a.get("outstanding_balance", a.get("balance", 0)))
        for a in stage3_accounts
    )
    npl_ratio = (stage3_total / loan_total * 100.0) if loan_total > 0 else 0.0

    by_aging: Dict[str, float] = {"30-60": 0, "60-90": 0, "90-180": 0, "180+": 0}
    for a in stage3_accounts:
        days = int(a.get("days_past_due", 90))
        bal = float(a.get("outstanding_balance", a.get("balance", 0)))
        if days < 60:
            by_aging["30-60"] += bal
        elif days < 90:
            by_aging["60-90"] += bal
        elif days < 180:
            by_aging["90-180"] += bal
        else:
            by_aging["180+"] += bal

    return {
        "_doc": "Computed NPL inventory aggregate (v8.10 --from-cbs).",
        "_schema_version": "1.0",
        "stage_3_kes": _safe_decimal_str(stage3_total),
        "loan_book_basis_kes": _safe_decimal_str(loan_total),
        "npl_ratio_pct": f"{npl_ratio:.1f}",
        "by_aging_kes": {k: _safe_decimal_str(v) for k, v in by_aging.items()},
    }


def _aggregate_customers_from_cbs(customers: list) -> Dict[str, Any]:
    """Aggregate customer base from customers.json. v8.10."""
    total = len(customers)
    by_segment: Dict[str, int] = {}
    by_tenure: Dict[str, int] = {}
    by_channel: Dict[str, int] = {}
    by_kyc: Dict[str, int] = {}
    for c in customers:
        seg = c.get("segment", "RETAIL")
        by_segment[seg] = by_segment.get(seg, 0) + 1
        tenure_yrs = c.get("tenure_years", 0)
        if tenure_yrs < 1:
            band = "<1y"
        elif tenure_yrs < 3:
            band = "1-3y"
        elif tenure_yrs < 5:
            band = "3-5y"
        else:
            band = "5y+"
        by_tenure[band] = by_tenure.get(band, 0) + 1
        ch = c.get("onboarding_channel", "BRANCH")
        by_channel[ch] = by_channel.get(ch, 0) + 1
        risk = c.get("kyc_risk_band", "LOW")
        by_kyc[risk] = by_kyc.get(risk, 0) + 1

    return {
        "_doc": "Computed customer base aggregate (v8.10 --from-cbs).",
        "_schema_version": "1.0",
        "total_customers": total,
        "by_segment_count": by_segment,
        "by_tenure_band_count": by_tenure,
        "by_onboarding_channel_count": by_channel,
        "by_kyc_risk_band_count": by_kyc,
        "monthly_growth_rate_pct": "1.5",  # Requires time-series; use default
    }


def _aggregate_dormant_from_cbs(accounts: list, customers: list) -> Dict[str, Any]:
    """Aggregate dormant accounts from accounts.json + customers.json. v8.10."""
    dormant_accounts = [a for a in accounts if a.get("is_dormant", False)]
    total_dormant = len(dormant_accounts)
    customer_basis = len(customers)
    dormancy_rate = (total_dormant / customer_basis * 100.0) if customer_basis > 0 else 0.0

    by_band: Dict[str, int] = {"6-12mo": 0, "12-24mo": 0, "24mo+": 0}
    by_segment_count: Dict[str, int] = {}
    total_balance = 0.0
    reactivation_count = 0
    for a in dormant_accounts:
        months = int(a.get("dormant_months", 12))
        if months < 12:
            by_band["6-12mo"] += 1
        elif months < 24:
            by_band["12-24mo"] += 1
        else:
            by_band["24mo+"] += 1
        seg = a.get("segment", a.get("customer_segment", "RETAIL"))
        by_segment_count[seg] = by_segment_count.get(seg, 0) + 1
        bal = float(a.get("balance", 0))
        total_balance += bal
        if months < 18 and bal > 1000:  # heuristic
            reactivation_count += 1

    avg_balance = (total_balance / total_dormant) if total_dormant > 0 else 0.0
    latent_value = total_balance * 0.3  # heuristic: 30% recoverable

    return {
        "_doc": "Computed dormant accounts aggregate (v8.10 --from-cbs).",
        "_schema_version": "1.0",
        "total_dormant": total_dormant,
        "customer_basis_count": customer_basis,
        "dormancy_rate_pct": f"{dormancy_rate:.1f}",
        "by_dormancy_band_count": by_band,
        "by_segment_count": by_segment_count,
        "reactivation_potential_count": reactivation_count,
        "avg_balance_per_dormant_kes": _safe_decimal_str(avg_balance),
        "estimated_latent_value_kes": _safe_decimal_str(latent_value),
    }


def write_aggregates_from_cbs(out_dir: Path, dry_run: bool = False) -> int:
    """v8.10: aggregate from real CBS source files (customers.json +
    accounts.json + transactions.json) instead of demo defaults.

    Returns count of files written. Raises FileNotFoundError if any
    required source is missing — callers should check via _check_cbs_sources()
    first and decide whether to fall back to generative mode.
    """
    customers = _load_cbs_source(out_dir, "customers.json")
    accounts = _load_cbs_source(out_dir, "accounts.json")
    if customers is None or accounts is None:
        raise FileNotFoundError(
            "Required CBS source files missing or unreadable in "
            f"{out_dir}/. Expected customers.json + accounts.json. "
            "Run without --from-cbs or generate the source files first."
        )

    # transactions.json is optional (used for trend detection in future);
    # don't require it for v8.10's static aggregation
    _ = _load_cbs_source(out_dir, "transactions.json")

    # Compute loan_total once — used by deposits (LDR) and NPL (basis)
    loan_accounts = [
        a for a in accounts
        if a.get("account_type", "").upper() in ("LOAN", "MORTGAGE", "TERM_LOAN")
    ]
    loan_total = sum(
        float(a.get("outstanding_balance", a.get("balance", 0)))
        for a in loan_accounts
    )

    aggregates = [
        ("loans_aggregate.json", _aggregate_loans_from_cbs(accounts)),
        ("deposits_aggregate.json", _aggregate_deposits_from_cbs(accounts, loan_total)),
        ("npl_aggregate.json", _aggregate_npl_from_cbs(accounts, loan_total)),
        ("customer_aggregate.json", _aggregate_customers_from_cbs(customers)),
        ("dormant_aggregate.json", _aggregate_dormant_from_cbs(accounts, customers)),
    ]

    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for filename, payload in aggregates:
        target = out_dir / filename
        if dry_run:
            print(f"  [DRY-RUN] would write {target} "
                  f"({len(json.dumps(payload))} chars from CBS)")
        else:
            target.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False),
                encoding="utf-8")
            print(f"  ✓ wrote {target} (computed from CBS sources)")
        written += 1
    return written


def write_aggregates(out_dir: Path, dry_run: bool = False) -> int:
    """Write all 5 CBS aggregate files. Returns number written."""
    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for filename, generator in GENERATORS:
        target = out_dir / filename
        payload = generator()
        if dry_run:
            print(f"  [DRY-RUN] would write {target} ({len(json.dumps(payload))} chars)")
        else:
            target.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False),
                encoding="utf-8")
            print(f"  ✓ wrote {target}")
        written += 1
    return written


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate CBS aggregate JSON files for the v7.10/v7.11 "
                    "FLEXCUBE Anti-Corruption Layer aggregator.")
    parser.add_argument(
        "--out", default="cbs_data",
        help="Output directory (default: cbs_data)")
    parser.add_argument(
        "--from-cbs", action="store_true",
        help="Compute from real CBS source files (customers.json + "
             "accounts.json + transactions.json) instead of demo "
             "defaults. v8.10 implementation. Falls back to generative "
             "mode with a clear message if source files are missing.")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be written without actually writing.")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    print(f"A2Z MIS 360 — CBS aggregate writer (v7.14 + v8.10)")
    print(f"Output directory: {out_dir.resolve()}")

    if args.from_cbs:
        # v8.10: real aggregation if sources present; graceful fallback otherwise.
        sources = _check_cbs_sources(out_dir)
        missing = [name for name, present in sources.items() if not present]
        if missing:
            print(f"⚠ --from-cbs requested but source files missing: "
                  f"{missing}")
            print(f"  Falling back to generative mode (demo defaults).")
            print(f"  To use --from-cbs, place customers.json + accounts.json "
                  f"+ transactions.json in {out_dir}/ first.")
            try:
                written = write_aggregates(out_dir, dry_run=args.dry_run)
            except Exception as e:
                print(f"ERROR: {e}", file=sys.stderr)
                return 1
        else:
            print(f"✓ --from-cbs: source files found "
                  f"(customers + accounts + transactions). Computing aggregates.")
            try:
                written = write_aggregates_from_cbs(
                    out_dir, dry_run=args.dry_run)
            except Exception as e:
                print(f"ERROR: {e}", file=sys.stderr)
                return 1
    else:
        # Default: generative mode (demo defaults, ACL-shape preserving)
        try:
            written = write_aggregates(out_dir, dry_run=args.dry_run)
        except Exception as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 1

    print(f"\n{'[dry-run]' if args.dry_run else '✓'} {written} aggregate "
          f"files {'would be written' if args.dry_run else 'written'} to {out_dir}")
    print(f"  ACL aggregator (utils/flexcube_aggregator.py) will pick them up "
          f"on next read when mode=synthetic.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
